version: '3'

tasks:
  up:
    desc: Start infrastructure
    cmds:
      - docker compose up -d

  down:
    desc: Stop infrastructure
    cmds:
      - docker compose down

  dev:
    desc: Start Tilt development environment
    cmds:
      - tilt up

  proto:
    desc: Generate protobuf code
    dir: shared/proto
    cmds:
      - buf generate

  test:
    desc: Run tests for all services
    cmds:
      - go test -v ./test-service/...

  load-test:
    desc: Run K6 load test
    cmds:
      - ./scripts/run-load-test.sh
