version: "3"

tasks:
  up:
    desc: Start infrastructure
    cmds:
      - docker compose up -d

  down:
    desc: Stop infrastructure
    cmds:
      - docker compose down

  dev:
    desc: Start Tilt development environment
    cmds:
      - tilt up

  proto:
    desc: Generate protobuf code
    dir: shared/proto
    cmds:
      - buf generate

  test:
    desc: Run tests for all services
    cmds:
      - go test -v ./test-service/...

  load-test:
    desc: Run K6 load test
    cmds:
      - ./scripts/run-load-test.sh

  cleanup:
    desc: Cleanup unused resources
    cmds:
      - ./scripts/docker-cleanup.sh

  clean-db:
    desc: Remove all data from application databases (Cassandra, Mongo, Neo4j, Postgres). Requires sudo.
    cmds:
      - task: down
      - cmd: echo "⚠️  Removing database data..."
      - cmd: sudo rm -rf data/cassandra data/mongo data/neo4j data/postgres data/meilisearch
      - cmd: echo "✅ Database data removed."
